<?php

/**
 * @file
 * Contains alloy_blog.module.
 */

use Drupal\Core\Routing\RouteMatchInterface;
use Drupal\views\Views;

/**
 * Implements hook_help().
 */
function alloy_blog_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the alloy_blog module.
    case 'help.page.alloy_blog':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('Coming Soon') . '</p>';
      return $output;

    default:
  }
}

function alloy_blog_theme($existing, $type, $theme, $path) {
  $theme = [];
  $theme['blog'] = [
    'render element' => 'elements',
    'file' => 'blog.page.inc',
    'template' => 'blog',
    'variables' => [
      'listing' => NULL,
    ],
  ];
  return $theme;
}

function alloy_blog_install() {
  // Enable pathauto for blog entities
  $config = \Drupal::service('config.factory')->getEditable('pathauto.settings');
  $enabled_pathauto_types = $config->get('enabled_entity_types');
  $enabled_pathauto_types[] = 'blog';
  $config->set('enabled_entity_types', $enabled_pathauto_types)->save();
}

function alloy_blog_preprocess_node(&$variables) {
  $node = $variables['elements']['#node'];
  $type = $node->getType();
  $id = $node->get('nid')->value;

  if ($type == 'blog_post') {
    // Add author bio
    $args = [$id];
    $view = Views::getView('author');
    $display = 'bio_block';
    if (is_object($view)) {
      $view->setArguments($args);
      $view->setDisplay($display);
      $view->preExecute();
      $view->execute();
      $variables['content']['author_bio'] = $view->buildRenderable($display, $args);
    }
  }
}
